services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27019:27017"        # opcional, solo si quieres acceder desde el host (Compass, etc.)
    volumes:
      - mongo-data:/data/db  # persistencia de Mongo

  acquire:
    build: .                # usa tu Dockerfile de este proyecto
    image: acquire:1.2      # nombre de imagen (opcional pero Ãºtil)
    container_name: acquire
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env.docker          # variables de entorno para este servicio
    ports:
      - "3001:3001"        # host:contenedor

volumes:
  mongo-data: